__END__

=head1 NAME

Irssi::Chatnet

=head1 FIELDS

Chatnet->{}

  type - "CHATNET" text
  chat_type - String ID of chat protocol, for example "IRC"

  name - name of chat network

  nick - if not empty, nick preferred in this network
  username - if not empty, username preferred in this network
  realname - if not empty, realname preferred in this network

  own_host - address to use when connecting this network
  autosendcmd - command to send after connecting to this network


=head1 METHODS

I<None found yet>
