__END__

=head1 NAME

Irssi::Ignore

=head1 FIELDS

C<Ignore-E<gt>{}>

  mask - Ignore mask
  servertag - Ignore only in server
  channels - Ignore only in channels (list of names)
  pattern - Ignore text pattern

  level - Ignore level

  exception - This is an exception ignore
  regexp - Regexp pattern matching
  fullword - Pattern matches only full words

=head1 METHODS

=head2 C<add_rec>

=head2 C<update_rec>

