__END__

=head1 NAME

Irssi::Irc

=head1 DESCRIPTION

=head1 CLASSES

=head1 EXPORTS

=head1 METHODS

=head2 TODO

    Irssi::Irc::dcc_chat_find_id
    Irssi::Irc::dcc_chat_send
    Irssi::Irc::dcc_ctcp_message
    Irssi::Irc::dcc_find_request
    Irssi::Irc::dcc_find_request_latest
    Irssi::Irc::dcc_get_download_path
    Irssi::Irc::dcc_register_type
    Irssi::Irc::dcc_str2type
    Irssi::Irc::dcc_type2str
    Irssi::Irc::dcc_unregister_type
    Irssi::Irc::dccs
    Irssi::Irc::deinit
    Irssi::Irc::get_mask
    Irssi::Irc::init
    Irssi::Irc::modes_join
    Irssi::Irc::notifies
    Irssi::Irc::notifylist_add
    Irssi::Irc::notifylist_find
    Irssi::Irc::notifylist_ison
    Irssi::Irc::notifylist_remove

=head2 Accessors

=head3 C<dccs>

returns a list of all L<DCC connections|Irssi::Irc::Dcc>

=head1 COPYRIGHT

All the content of this site is copyright E<copy> 2000-2010 L<The Irssi
project|http://irssi.org>.

Formatting to POD and linking by Tom Feist
 L<shabble+irssi@metavore.org|mailto:shabble+irssi@metavore.org>

