__END__

=head1 NAME

Irssi::Log

=head1 FIELDS

C<Log-E<gt>{}>

  fname - Log file name
  real_fname - The actual opened log file (after %d.%m.Y etc. are expanded)
  opened - Log file is open
  level - Log only these levels
  last - Timestamp when last message was written
  autoopen - Automatically open log at startup
  failed - Opening log failed last time
  temp - Log isn't saved to config file
  items - List of log items


=head1 METHODS

=head2 C<update>

Add log to list of logs / save changes to config file.

=head2 C<close>

Destroy log file.

=head2 C<start_logging>

Open log file and start logging.

=head2 C<stop_logging>

Close log file.

=head2 C<item_add $type, $name, $server>

Add log item to log.

=head2 C<item_destroy $item>

Remove log item from log.

=head2 C<item_find $type, $item, $server>

Find item from log. Returns L<Irssi::Logitem>

=head2 C<write_rec>

I<Undocumented>

