__END__

=head1 NAME

Irssi::Nick

=head1 FIELDS

C<Nick-E<gt>{}>

  type - "NICK" text
  chat_type - String ID of chat protocol, for example "IRC"

  nick - Plain nick
  host - Host address
  realname - Real name
  hops - Hop count to the server the nick is using

  gone, serverop - User status, 1 or 0
  op, voice, halfop - Channel status, 1 or 0

  last_check - timestamp when last checked gone/ircop status.
  send_massjoin - Waiting to be sent in a "massjoin" signal, 1 or 0

=head1 METHODS
