__END__

=head1 NAME

Irssi::Rawlog

=head1 FIELDS


C<Rawlog-E<gt>{}>

  logging - The rawlog is being written to file currently
  nlines - Number of lines in rawlog

=head1 METHODS

=head2 C<destroy>

Destroy the rawlog.

=head2 C<get_lines>

Returns all lines in rawlog.

=head2 C<open $filename>

Start logging new messages in rawlog to specified file.

=head2 C<close>

Stop logging to file.

=head2 C<save $filename>

Save the current rawlog history to specified file.

=head2 C<input $str>

Send `str' to raw log as input text.

=head2 C<output $str>

Send `str' to raw log as output text.

=head2 C<redirect $str>

Send `str' to raw log as redirection text.

